#!/bin/sh

PATH="$PATH:/opt/wz_mini/tmp/.bin"

get_host() {
  nslookup -type=a "$1" 1.1.1.1 | grep -e "^Address: [[:digit:]]" | cut -d " " -f2 | xargs -I {} -n 1 echo {} $1 | shuf | head -n1
}

echo 127.0.0.1	localhost

i=1
while [ "$i" -le "$#" ]; do
  eval "arg=\${$i}"
  get_host $arg
  i=$((i + 1))
done

